export const idpaAnnouncement = {
  date: '2026-10-04',
  source: 'https://www.idpa.com/clubs/gdsff/',
  clubId: 'CL100829',
  en: {
    eyebrow: 'Federation News',
    dateLabel: '4 October 2026',
    title: 'GDSFF joins IDPA; five federation instructors earn Safety Officer certification',
    summary: 'Five GDSFF instructors are now IDPA Safety Officers, and GDSFF is officially listed as IDPA club CL100829.',
    lead: 'Five GDSFF instructors completed the IDPA Safety Officer course on 2 October 2026 and earned their SO certification. The course was led by Federico Iannelli (IT1349).',
    rosterLabel: 'The five GDSFF instructors',
    club: 'GDSFF is also officially listed in the International Defensive Pistol Association’s club directory as Gdsff, club ID CL100829, with a joining date of 2 October 2026.',
    text: 'These milestones support the federation’s work to strengthen safety standards and develop dynamic shooting in Georgia.',
    readMore: 'Read the announcement',
    teamLabel: 'Meet our Safety Officers & Instructors',
    sourceLabel: 'Official IDPA club listing',
  },
  ka: {
    eyebrow: 'ფედერაციის სიახლეები',
    dateLabel: '4 ოქტომბერი, 2026',
    title: 'GDSFF IDPA-ს შეუერთდა; ფედერაციის ხუთმა ინსტრუქტორმა უსაფრთხოების ოფიცრის სერტიფიკატი მიიღო',
    summary: 'GDSFF-ის ხუთი ინსტრუქტორი IDPA-ს უსაფრთხოების ოფიცერი გახდა, ხოლო GDSFF ოფიციალურად არის წარმოდგენილი IDPA-ს კლუბების რეესტრში ნომრით CL100829.',
    lead: 'GDSFF-ის ხუთმა ინსტრუქტორმა 2026 წლის 2 ოქტომბერს IDPA-ს უსაფრთხოების ოფიცრის კურსი გაიარა და SO სერტიფიკატი მიიღო. კურსს ფედერიკო იანელი (Federico Iannelli, IT1349) უძღვებოდა.',
    rosterLabel: 'GDSFF-ის ხუთი ინსტრუქტორი',
    club: 'GDSFF ასევე ოფიციალურად არის წარმოდგენილი თავდაცვითი პისტოლეტით სროლის საერთაშორისო ასოციაციის (IDPA) კლუბების რეესტრში სახელწოდებით Gdsff, კლუბის ნომრით CL100829. რეესტრში გაწევრიანების თარიღად მითითებულია 2026 წლის 2 ოქტომბერი.',
    text: 'ეს ნაბიჯები ხელს უწყობს ფედერაციის მუშაობას საქართველოში უსაფრთხოების სტანდარტების განმტკიცებისა და დინამიური სროლის განვითარებისთვის.',
    readMore: 'განცხადების წაკითხვა',
    teamLabel: 'ჩვენი უსაფრთხოების ოფიცრები და ინსტრუქტორები',
    sourceLabel: 'IDPA-ს კლუბების ოფიციალური რეესტრი',
  },
}
