const sharedParticipantFields = {
  ka: [
    { name: 'fullName', label: 'სახელი და გვარი', type: 'text', autoComplete: 'name' },
    { name: 'birthDate', label: 'დაბადების თარიღი', type: 'date' },
    { name: 'personalId', label: 'პირადი ნომერი / საიდენტიფიკაციო ნომერი', type: 'text' },
    { name: 'citizenship', label: 'მოქალაქეობა', type: 'text' },
    { name: 'address', label: 'მისამართი', type: 'textarea', rows: 3 },
    { name: 'phone', label: 'ტელეფონი', type: 'tel', autoComplete: 'tel' },
    { name: 'email', label: 'ელფოსტა', type: 'email', autoComplete: 'email' },
    {
      name: 'status',
      label: 'წევრის / მონაწილის სტატუსი',
      type: 'select',
      options: ['წევრი', 'სპორტსმენი', 'მწვრთნელი', 'სტუმარი', 'სხვა'],
    },
    { name: 'emergencyContactName', label: 'საგანგებო საკონტაქტო პირი', type: 'text' },
    { name: 'emergencyContactPhone', label: 'საგანგებო საკონტაქტო ტელეფონი', type: 'tel' },
  ],
  en: [
    { name: 'fullName', label: 'Full name', type: 'text', autoComplete: 'name' },
    { name: 'birthDate', label: 'Date of birth', type: 'date' },
    { name: 'personalId', label: 'Personal / identification number', type: 'text' },
    { name: 'citizenship', label: 'Citizenship', type: 'text' },
    { name: 'address', label: 'Address', type: 'textarea', rows: 3 },
    { name: 'phone', label: 'Phone', type: 'tel', autoComplete: 'tel' },
    { name: 'email', label: 'Email', type: 'email', autoComplete: 'email' },
    {
      name: 'status',
      label: 'Member / participant status',
      type: 'select',
      options: ['Member', 'Athlete', 'Coach', 'Guest', 'Other'],
    },
    { name: 'emergencyContactName', label: 'Emergency contact person', type: 'text' },
    { name: 'emergencyContactPhone', label: 'Emergency contact phone', type: 'tel' },
  ],
}

export const safetyConsentContent = {
  ka: {
    title: 'უსაფრთხოების წესები და ინფორმირებული თანხმობა',
    optionalTitle: 'Safety Rules & Informed Consent',
    eyebrow: 'ფედერაციის შიდა საორგანიზაციო ფორმა',
    highlights: ['აუცილებელი ველები', 'ონლაინ ხელმოწერა', 'PDF ექსპორტი'],
    introText:
      'საქართველოს დინამიური სროლისა და ფუნქციური ფიტნესის ფედერაციის უსაფრთხოების წესები და ინფორმირებული თანხმობის ფორმა განკუთვნილია წევრებისთვის, სპორტსმენებისთვის, მონაწილეებისთვის და სხვა შესაბამისი პირებისთვის. დოკუმენტი განსაზღვრავს უსაფრთხოების ძირითად წესებს, მონაწილის პასუხისმგებლობას, დისციპლინურ მოთხოვნებსა და ინფორმირებული თანხმობის პირობებს.',
    note: 'ფორმის შევსებამდე გთხოვთ ყურადღებით გაეცნოთ ყველა პუნქტს.',
    introCardTitle: 'ოფიციალური ელექტრონული ფორმა',
    introCardText:
      'ფორმა განკუთვნილია უსაფრთხოების გაცნობის, თანხმობის დაფიქსირების, ონლაინ ხელმოწერისა და შემდგომი ადმინისტრაციული დამუშავებისთვის.',
    participantSectionTitle: 'მონაწილის მონაცემები',
    participantSectionText: 'შეავსეთ ყველა სავალდებულო მონაცემი ზუსტად და სრულად.',
    participantFields: sharedParticipantFields.ka,
    safetySectionTitle: 'უსაფრთხოების დადასტურება',
    safetySectionText: 'ყველა ქვემოთ მოცემული პუნქტი სავალდებულოა.',
    safetyItems: [
      'ვადასტურებ, რომ გავეცანი ფედერაციის უსაფრთხოების წესებს.',
      'ვადასტურებ, რომ დავემორჩილები ინსტრუქტორის, ორგანიზატორისა და ფედერაციის უფლებამოსილი წარმომადგენლების მითითებებს.',
      'ვადასტურებ, რომ დავიცავ დისციპლინურ და უსაფრთხოების მოთხოვნებს.',
      'ვადასტურებ, რომ უსაფრთხოების წესების დარღვევის შემთხვევაში ფედერაცია უფლებამოსილია შემიზღუდოს მონაწილეობა.',
      'ვადასტურებ, რომ მონაწილეობისას ვიმოქმედებ პასუხისმგებლობით და წესების დაცვით.',
    ],
    consentSectionTitle: 'ჯანმრთელობა / ინფორმირებული თანხმობა',
    consentSectionText: 'გთხოვთ დაადასტუროთ ქვემოთ ჩამოთვლილი პირობები.',
    consentItems: [
      'ვადასტურებ, რომ ჩემი ჯანმრთელობის მდგომარეობა მაძლევს მონაწილეობის შესაძლებლობას.',
      'ვადასტურებ, რომ მონაწილეობას ვიღებ ინფორმირებული თანხმობის საფუძველზე.',
      'ვაცნობიერებ, რომ სპორტულ/სასწავლო აქტივობებში მონაწილეობა დაკავშირებულია გარკვეულ რისკებთან.',
      'ვადასტურებ, რომ სწორად და სრულად შევავსე მოცემული ინფორმაცია.',
    ],
    signatureSectionTitle: 'ხელმოწერა',
    signatureSectionText: 'ხელმოწერა აუცილებელია როგორც ფორმის გაგზავნისთვის, ასევე PDF ექსპორტისთვის.',
    signerNameLabel: 'ხელმომწერის სრული სახელი',
    signerNameHint: 'შეიყვანეთ სრული სახელი ისე, როგორც უნდა აისახოს დოკუმენტში.',
    signatureLabel: 'მონაწილის ხელმოწერა',
    signatureHint: 'ხელი მოაწერეთ მაუსით ან სენსორული ეკრანით.',
    signatureClearLabel: 'ხელმოწერის გასუფთავება',
    signatureDateLabel: 'ხელმოწერის თარიღი',
    signatureSignedLabel: 'ხელმოწერა დაფიქსირებულია',
    signaturePendingLabel: 'ხელმოწერა სავალდებულოა',
    minorToggleLabel: 'ვარ არასრულწლოვანი',
    guardianSectionTitle: 'მშობლის / კანონიერი წარმომადგენლის მონაცემები',
    guardianSectionText: 'არასრულწლოვანი მონაწილის შემთხვევაში ქვემოთ მოცემული მონაცემები და ხელმოწერა სავალდებულოა.',
    guardianNameLabel: 'მშობლის / კანონიერი წარმომადგენლის სახელი და გვარი',
    guardianPhoneLabel: 'მშობლის / კანონიერი წარმომადგენლის ტელეფონი',
    guardianSignatureLabel: 'მშობლის / კანონიერი წარმომადგენლის ხელმოწერა',
    declarationSectionTitle: 'საბოლოო დადასტურება',
    declarationText:
      'ვადასტურებ, რომ სრულად გავეცანი წარმოდგენილ წესებსა და პირობებს, ინფორმაცია შევავსე სწორად, ხელმოწერას ვაკეთებ ნებაყოფლობით და ვადასტურებ ჩემს თანხმობას დოკუმენტში მოცემულ პირობებზე.',
    footerNote:
      'ეს ონლაინ ფორმა წარმოადგენს ფედერაციის შიდა ადმინისტრაციულ და საორგანიზაციო დოკუმენტს. საჭიროების შემთხვევაში ფედერაცია უფლებამოსილია მოითხოვოს დამატებითი იდენტიფიკაცია ან ფიზიკურად ხელმოწერილი ვერსია.',
    actionDownload: 'PDF-ის ჩამოტვირთვა',
    actionSubmit: 'ფორმის გაგზავნა',
    actionReset: 'გასუფთავება',
    submitReadyText: 'გაგზავნის ლოგიკა მომზადებულია frontend-იდან email/API/backend ინტეგრაციისთვის.',
    submitSuccessTitle: 'ფორმა მიღებულია შიდა დამუშავებისთვის',
    submitSuccessText: 'ტესტური ელექტრონული გაგზავნა წარმატებით შესრულდა. საცნობარო კოდი:',
    validationSignature: 'გთხოვთ, დაამატოთ მონაწილის ხელმოწერა.',
    validationGuardianSignature: 'გთხოვთ, დაამატოთ მშობლის / კანონიერი წარმომადგენლის ხელმოწერა.',
    validationGuardianFields: 'არასრულწლოვანი მონაწილისთვის შეავსეთ მშობლის / წარმომადგენლის მონაცემები.',
    validationSubmit: 'გთხოვთ, შეავსოთ ყველა სავალდებულო ველი და მონიშნოთ ყველა სავალდებულო დადასტურება.',
    resetConfirmation: 'ფორმა გასუფთავებულია.',
    pdfFilePrefix: 'GDSFF_Safety_Consent',
    yes: 'დიახ',
    no: 'არა',
  },
  en: {
    title: 'Safety Rules & Informed Consent',
    optionalTitle: 'უსაფრთხოების წესები და ინფორმირებული თანხმობა',
    eyebrow: 'Federation Internal Operational Form',
    highlights: ['Required fields', 'Online signature', 'PDF export'],
    introText:
      'The Georgian Dynamic Shooting & Functional Fitness Federation safety rules and informed consent form is intended for members, athletes, participants, and other relevant persons. The document defines the core safety rules, participant responsibilities, disciplinary requirements, and the terms of informed consent.',
    note: 'Please review every point carefully before completing the form.',
    introCardTitle: 'Official electronic workflow',
    introCardText:
      'This form is designed for safety acknowledgment, informed consent capture, online signature, and later administrative processing.',
    participantSectionTitle: 'Participant details',
    participantSectionText: 'Complete all required information accurately and in full.',
    participantFields: sharedParticipantFields.en,
    safetySectionTitle: 'Safety acknowledgment',
    safetySectionText: 'Every acknowledgment below is required.',
    safetyItems: [
      'I confirm that I have reviewed the federation safety rules.',
      'I confirm that I will follow the instructions of the instructor, organizer, and authorized federation representatives.',
      'I confirm that I will comply with disciplinary and safety requirements.',
      'I confirm that the federation may restrict my participation in the event of a breach of safety rules.',
      'I confirm that I will act responsibly and in compliance with the rules during participation.',
    ],
    consentSectionTitle: 'Health / informed consent',
    consentSectionText: 'Please confirm the following required conditions.',
    consentItems: [
      'I confirm that my health condition allows me to participate.',
      'I confirm that I participate on the basis of informed consent.',
      'I understand that participation in sport / training activities involves certain risks.',
      'I confirm that I have completed the provided information correctly and fully.',
    ],
    signatureSectionTitle: 'Signature',
    signatureSectionText: 'A signature is required both for submission and for PDF export.',
    signerNameLabel: 'Typed full name',
    signerNameHint: 'Enter the full name exactly as it should appear in the document.',
    signatureLabel: 'Participant signature',
    signatureHint: 'Draw your signature using a mouse or touch input.',
    signatureClearLabel: 'Clear signature',
    signatureDateLabel: 'Signature date',
    signatureSignedLabel: 'Signature captured',
    signaturePendingLabel: 'Signature required',
    minorToggleLabel: 'I am a minor',
    guardianSectionTitle: 'Parent / legal guardian details',
    guardianSectionText: 'For a minor participant, the following details and guardian signature are required.',
    guardianNameLabel: 'Parent / legal guardian full name',
    guardianPhoneLabel: 'Parent / legal guardian phone',
    guardianSignatureLabel: 'Parent / legal guardian signature',
    declarationSectionTitle: 'Final declaration',
    declarationText:
      'I confirm that I have fully reviewed the presented rules and conditions, that I have completed the information correctly, that I sign voluntarily, and that I confirm my consent to the conditions contained in this document.',
    footerNote:
      'This online form constitutes an internal administrative and organizational federation document. Where necessary, the federation may request additional identification or a physically signed version.',
    actionDownload: 'Download PDF',
    actionSubmit: 'Submit Form',
    actionReset: 'Reset Form',
    submitReadyText: 'The submission flow is structured for easy later connection to email, API, or database storage.',
    submitSuccessTitle: 'Form accepted for internal processing',
    submitSuccessText: 'The frontend-ready electronic submission completed successfully. Reference code:',
    validationSignature: 'Please add the participant signature.',
    validationGuardianSignature: 'Please add the parent / legal guardian signature.',
    validationGuardianFields: 'Please complete the parent / guardian details for a minor participant.',
    validationSubmit: 'Please complete all required fields and acknowledgments.',
    resetConfirmation: 'The form has been cleared.',
    pdfFilePrefix: 'GDSFF_Safety_Consent',
    yes: 'Yes',
    no: 'No',
  },
}
