const supportTypeOptions = {
  en: [
    { value: 'corporate-sponsorship', label: 'Corporate Sponsorship' },
    { value: 'event-sponsorship', label: 'Event Sponsorship' },
    { value: 'equipment-support', label: 'Equipment Support' },
    { value: 'infrastructure-support', label: 'Infrastructure Support' },
    { value: 'individual-donation', label: 'Individual Donation' },
    { value: 'strategic-partnership', label: 'Strategic Partnership' },
    { value: 'other', label: 'Other' },
  ],
  ka: [
    { value: 'corporate-sponsorship', label: 'კორპორაციული სპონსორობა' },
    { value: 'event-sponsorship', label: 'ღონისძიების სპონსორობა' },
    { value: 'equipment-support', label: 'ინვენტარით მხარდაჭერა' },
    { value: 'infrastructure-support', label: 'ინფრასტრუქტურული მხარდაჭერა' },
    { value: 'individual-donation', label: 'ინდივიდუალური დონაცია' },
    { value: 'strategic-partnership', label: 'სტრატეგიული პარტნიორობა' },
    { value: 'other', label: 'სხვა' },
  ],
}

export const supportContent = {
  en: {
    navLabel: 'Support',
    heroEyebrow: 'Support',
    title: 'Sponsorship & Donations',
    heroSubtitle: 'Support the development of dynamic shooting and functional fitness in Georgia',
    intro: [
      'The Georgian Dynamic Shooting and Functional Fitness Federation welcomes support from individuals, companies, and strategic partners who want to contribute to the development of dynamic shooting, functional fitness, athlete preparation, infrastructure, and international sports cooperation in Georgia.',
      'Support can be provided through sponsorship, donations, partnership programs, event support, equipment assistance, and development initiatives.',
    ],
    supportAreasTitle: 'Support Areas',
    supportAreas: [
      {
        title: 'Corporate Sponsorship',
        text: 'Support federation development programs, competitions, athlete preparation, and long-term initiatives.',
      },
      {
        title: 'Event Sponsorship',
        text: 'Support championships, training events, demonstration activities, and international sports cooperation projects.',
      },
      {
        title: 'Equipment Support',
        text: 'Contribute sports, safety, technical, fitness, or operational equipment for federation activities and athlete preparation.',
      },
      {
        title: 'Infrastructure Support',
        text: 'Help strengthen training grounds, event spaces, operational systems, and sport development capacity.',
      },
      {
        title: 'Individual Donations',
        text: "Support the federation's long-term development through individual financial contributions.",
      },
      {
        title: 'Strategic Partnership',
        text: 'Partner with the federation on long-term national and international development projects.',
      },
    ],
    whyTitle: 'Why Support the Federation',
    whyItems: [
      'Development of a new and growing sport direction in Georgia',
      'Support for athlete preparation and youth engagement',
      'Promotion of sports tourism and international cooperation',
      'Contribution to a disciplined, healthy, and competitive sport culture',
      'Participation in building modern sport infrastructure',
    ],
    inquiryTitle: 'Sponsorship & Donation Inquiry',
    inquiryText:
      'If you are interested in supporting the federation through sponsorship, donation, or partnership, please contact us through our official communication channels.',
    discussionTitle: 'We are available to discuss:',
    discussionItems: [
      'sponsorship opportunities',
      'development partnerships',
      'event cooperation',
      'branding opportunities',
      'equipment and infrastructure support',
      'custom contribution formats',
    ],
    transparencyTitle: 'Transparency / Official Note',
    transparencyNote:
      'All sponsorship and donation discussions are handled individually and officially through the federation. Upon request, additional information can be provided regarding cooperation structure, branding opportunities, support scope, and project format.',
    ctas: [
      'Become a Sponsor',
      'Make a Donation',
      'Request Partnership Details',
      'Contact the Federation',
    ],
    form: {
      title: 'Inquiry Form',
      text: 'Share your support interest and a federation representative will follow up through official channels.',
      fields: [
        { name: 'fullName', label: 'Full Name', type: 'text', autoComplete: 'name', placeholder: 'Enter full name' },
        {
          name: 'organization',
          label: 'Company / Organization',
          type: 'text',
          required: false,
          autoComplete: 'organization',
          placeholder: 'Enter company or organization',
        },
        { name: 'email', label: 'Email', type: 'email', autoComplete: 'email', placeholder: 'Enter email address' },
        {
          name: 'phone',
          label: 'Phone Number',
          type: 'tel',
          required: false,
          autoComplete: 'tel',
          inputMode: 'tel',
          placeholder: 'Enter phone number',
        },
        {
          name: 'supportType',
          label: 'Type of Support',
          type: 'select',
          options: supportTypeOptions.en,
          placeholder: 'Select support type',
        },
        {
          name: 'budget',
          label: 'Estimated Budget / Contribution',
          type: 'text',
          required: false,
          placeholder: 'Enter estimated budget or contribution',
        },
        {
          name: 'message',
          label: 'Message',
          type: 'textarea',
          rows: 5,
          placeholder: 'Share your inquiry details',
        },
      ],
      submitLabel: 'Submit Inquiry',
      validationTitle: 'Form Incomplete',
      validationText: 'Please complete all required fields before submitting.',
      successTitle: 'Inquiry Sent',
      successText: 'Your sponsorship and donation inquiry has been sent successfully.',
      errorTitle: 'Submission Failed',
      errorText: 'The inquiry could not be delivered right now. Please try again shortly.',
      referenceLabel: 'Reference',
    },
  },
  ka: {
    navLabel: 'მხარდაჭერა',
    heroEyebrow: 'მხარდაჭერა',
    title: 'სპონსორობა და დონაციები',
    heroSubtitle: 'მხარი დაუჭირეთ საქართველოში დინამიური სროლის და ფუნქციური ფიტნესის განვითარებას',
    intro: [
      'საქართველოს დინამიური სროლის და ფუნქციური ფიტნესის ფედერაცია მიესალმება იმ პირების, კომპანიებისა და სტრატეგიული პარტნიორების მხარდაჭერას, რომელთაც სურთ წვლილის შეტანა საქართველოში დინამიური სროლის, ფუნქციური ფიტნესის, სპორტსმენთა მომზადების, ინფრასტრუქტურისა და საერთაშორისო სპორტული თანამშრომლობის განვითარებაში.',
      'მხარდაჭერა შესაძლებელია სპონსორობის, დონაციის, პარტნიორული პროგრამების, ღონისძიებების მხარდაჭერის, ინვენტარით დახმარებისა და განვითარების ინიციატივების ფორმით.',
    ],
    supportAreasTitle: 'მხარდაჭერის მიმართულებები',
    supportAreas: [
      {
        title: 'კორპორაციული სპონსორობა',
        text: 'მხარდაჭერა ფედერაციის განვითარების პროგრამებისთვის, ჩემპიონატებისთვის, სპორტსმენთა მომზადებისა და გრძელვადიანი ინიციატივებისთვის.',
      },
      {
        title: 'ღონისძიებების სპონსორობა',
        text: 'მხარდაჭერა ჩემპიონატების, სასწავლო ღონისძიებების, საჩვენებელი აქტივობებისა და საერთაშორისო სპორტული თანამშრომლობის პროექტებისთვის.',
      },
      {
        title: 'ინვენტარით მხარდაჭერა',
        text: 'ფედერაციის საქმიანობისა და სპორტსმენთა მომზადებისთვის სპორტული, უსაფრთხოების, ტექნიკური, ფიტნესისა და საორგანიზაციო აღჭურვილობით დახმარება.',
      },
      {
        title: 'ინფრასტრუქტურული მხარდაჭერა',
        text: 'სავარჯიშო სივრცეების, ღონისძიების ზონების, ოპერაციული სისტემებისა და სპორტის განვითარების შესაძლებლობების გაძლიერებაში მონაწილეობა.',
      },
      {
        title: 'ინდივიდუალური დონაცია',
        text: 'ფედერაციის გრძელვადიანი განვითარების მხარდაჭერა ინდივიდუალური ფინანსური შემოწირულობის ფორმით.',
      },
      {
        title: 'სტრატეგიული პარტნიორობა',
        text: 'ფედერაციასთან გრძელვადიანი თანამშრომლობა ეროვნულ და საერთაშორისო განვითარების პროექტებში.',
      },
    ],
    whyTitle: 'რატომ უნდა დაუჭიროთ მხარი ფედერაციას',
    whyItems: [
      'საქართველოში ახალი და მზარდი სპორტული მიმართულების განვითარება',
      'სპორტსმენთა მომზადებისა და ახალგაზრდების ჩართულობის მხარდაჭერა',
      'სპორტული ტურიზმისა და საერთაშორისო თანამშრომლობის ხელშეწყობა',
      'დისციპლინირებული, ჯანსაღი და კონკურენტული სპორტული კულტურის გაძლიერება',
      'თანამედროვე სპორტული ინფრასტრუქტურის შექმნაში მონაწილეობა',
    ],
    inquiryTitle: 'სპონსორობისა და დონაციის მოთხოვნა',
    inquiryText:
      'თუ დაინტერესებული ხართ ფედერაციის მხარდაჭერით სპონსორობის, დონაციის ან პარტნიორობის ფორმით, გთხოვთ დაგვიკავშირდეთ ოფიციალური საკომუნიკაციო არხების საშუალებით.',
    discussionTitle: 'ჩვენ მზად ვართ განვიხილოთ:',
    discussionItems: [
      'სპონსორობის შესაძლებლობები',
      'განვითარების პარტნიორობა',
      'ღონისძიებების მხარდაჭერა',
      'ბრენდინგის შესაძლებლობები',
      'ინვენტარითა და ინფრასტრუქტურით მხარდაჭერა',
      'თანამშრომლობის ინდივიდუალური ფორმატები',
    ],
    transparencyTitle: 'გამჭვირვალობა / ოფიციალური შენიშვნა',
    transparencyNote:
      'სპონსორობასა და დონაციასთან დაკავშირებული ყველა საკითხი ინდივიდუალურად და ოფიციალური კომუნიკაციის გზით განიხილება ფედერაციასთან. მოთხოვნის შემთხვევაში შესაძლებელია დამატებითი ინფორმაციის მიწოდება თანამშრომლობის სტრუქტურაზე, ბრენდინგის შესაძლებლობებზე, მხარდაჭერის მასშტაბსა და პროექტის ფორმატზე.',
    ctas: [
      'გახდი სპონსორი',
      'გააკეთე დონაცია',
      'მოითხოვე პარტნიორობის დეტალები',
      'დაგვიკავშირდით',
    ],
    form: {
      title: 'მოთხოვნის ფორმა',
      text: 'გააზიარეთ თქვენი ინტერესის ფორმატი და ფედერაციის წარმომადგენელი დაგიკავშირდებათ ოფიციალური არხებით.',
      fields: [
        {
          name: 'fullName',
          label: 'სახელი და გვარი',
          type: 'text',
          autoComplete: 'name',
          placeholder: 'შეიყვანეთ სახელი და გვარი',
        },
        {
          name: 'organization',
          label: 'კომპანია / ორგანიზაცია',
          type: 'text',
          required: false,
          autoComplete: 'organization',
          placeholder: 'შეიყვანეთ კომპანია ან ორგანიზაცია',
        },
        {
          name: 'email',
          label: 'ელფოსტა',
          type: 'email',
          autoComplete: 'email',
          placeholder: 'შეიყვანეთ ელფოსტის მისამართი',
        },
        {
          name: 'phone',
          label: 'ტელეფონის ნომერი',
          type: 'tel',
          required: false,
          autoComplete: 'tel',
          inputMode: 'tel',
          placeholder: 'შეიყვანეთ ტელეფონის ნომერი',
        },
        {
          name: 'supportType',
          label: 'მხარდაჭერის ტიპი',
          type: 'select',
          options: supportTypeOptions.ka,
          placeholder: 'აირჩიეთ მხარდაჭერის ტიპი',
        },
        {
          name: 'budget',
          label: 'სავარაუდო ბიუჯეტი / შენატანი',
          type: 'text',
          required: false,
          placeholder: 'შეიყვანეთ სავარაუდო ბიუჯეტი ან შენატანი',
        },
        {
          name: 'message',
          label: 'შეტყობინება',
          type: 'textarea',
          rows: 5,
          placeholder: 'გააზიარეთ მოთხოვნის დეტალები',
        },
      ],
      submitLabel: 'მოთხოვნის გაგზავნა',
      validationTitle: 'ფორმა არასრულადაა შევსებული',
      validationText: 'გთხოვთ შეავსოთ ყველა სავალდებულო ველი გაგზავნამდე.',
      successTitle: 'მოთხოვნა გაიგზავნა',
      successText: 'თქვენი სპონსორობის/დონაციის მოთხოვნა წარმატებით გაიგზავნა.',
      errorTitle: 'გაგზავნა ვერ შესრულდა',
      errorText: 'მოთხოვნის მიწოდება ამ ეტაპზე ვერ მოხერხდა. გთხოვთ სცადოთ ხელახლა.',
      referenceLabel: 'რეფერენსი',
    },
  },
}
